### PR TITLE
Fix type issue with exported module

### LINKED ISSUE #9: typescript issue
When importing this in typescript I get a `TS2306` error. Any ideas how to fix this?

```
/node_modules/bycontract/index.d.ts' is not a module.
```

### PR DESCRIPTION
**Pull request by dworthen**
Resolves #9
- Remove dependency on deprecated tsc package.
All vulnerabilities reported by npm audit were due to depending
on tsc. Removing this dependency cleared vulnerabilities.
- Remove manually maintained index.d.ts. This file is not
necessary since package is written in TypeScript.
- Update tsconfig to support generating declaration files.
- Update package.json to load typings generated by TypeScript.

### CODE REVIEW

**Comment by OmgImAlexis** [comment]
@dsheiko any chance this could be looked at soon?

**Comment by OmgImAlexis** [comment]
I've confirmed switching to this version fixes the issue.

**Comment by dsheiko** [comment]
Great job, thanks

**Comment by OmgImAlexis** [comment]
Has this been published to npm yet?

**Comment by dsheiko** [comment]
https://www.npmjs.com/package/bycontract v2.0.9

**Pull request merged**
